# === Network Binding ===
# listen all interfaces 
#interface=vmbr0
interface

# === Local Zones & Resolution ===
local=/edge.arpa/

# wildcard for addresses in local zone
address=/edge.local/192.168.1.100
address=/edge.arpa/192.168.1.100
address=/edge.lan/192.168.1.100

address=/.*/192.168.1.100 # all unknown addresses

# === Upstream Resolution (external) ===
# recursive dns request, if address not found in local zone
server=1.1.1.1 # cloudflare
server=9.9.9.9 # Quad9
server=8.8.8.8 # google

# turn off resolv.conf, we own create server=.
no-resolv

# === DHCP & Clients (VM/LXC) ===
dhcp-range=192.168.10.50,192.168.10.200,12h   # internal: check ip
dhcp-option=option:router,192.168.10.1        # gateway
dhcp-option=option:dns-server,192.168.10.1    # 

# === Security & Performance ===
# block requests from ethernet
no-poll
cache-size=1000
log-dhcp        # log DHCP requests (debug)
log-queries     # log DNS queries (debug)

# === Specifics for Talos/K8s Environment ===
address=/edge/192.168.10.1 # host-ip
 
