source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto nic0
iface nic0 inet static
        address 192.168.1.100/24
        gateway 192.168.1.1
        metric 100
        post-up echo 1 > /proc/sys/net/ipv4/conf/nic0/proxy_arp

# auto wlp4s0
# iface wlp4s0 inet static
#         address 192.168.1.101/24
#         gateway 192.168.1.1
#         metric 200
#         wpa-ssid <TODO: SSID>
#         wpa-psk <TODO: pass>

auto vmbr0
iface vmbr0 inet static
        address 192.168.10.1/24
        bridge-ports none
        bridge-stp off
        bridge-fd 0

        post-up echo 1 > /proc/sys/net/ipv4/ip_forward


post-up   iptables -t nat -A POSTROUTING -s 192.168.10.0/24 -o nic0 -j MASQUERADE
post-down iptables -t nat -D POSTROUTING -s 192.168.10.0/24 -o nic0 -j MASQUERADE 2>/dev/null || true
#
post-up   iptables -t nat -A PREROUTING -d 192.168.1.100 -p tcp --dport 80 -j DNAT --to-destination 192.168.10.100:80
post-up   iptables -t nat -A PREROUTING -d 192.168.1.100 -p tcp --dport 443 -j DNAT --to-destination 192.168.10.100:443
post-up   iptables -t nat -A PREROUTING -d 192.168.1.100 -p tcp --dport 8080 -j DNAT --to-destination 192.168.10.100:8080
post-down iptables -t nat -D PREROUTING -d 192.168.1.100 -p tcp --dport 80 -j DNAT --to-destination 192.168.10.100:80 2>/dev/null || true
post-down iptables -t nat -D PREROUTING -d 192.168.1.100 -p tcp --dport 443 -j DNAT --to-destination 192.168.10.100:443 2>/dev/null || true
post-down iptables -t nat -D PREROUTING -d 192.168.1.100 -p tcp --dport 8080 -j DNAT --to-destination 192.168.10.100:8080 2>/dev/null || true
#
post-up   iptables -A FORWARD -d 192.168.10.100 -p tcp --dport 80 -j ACCEPT
post-up   iptables -A FORWARD -d 192.168.10.100 -p tcp --dport 443 -j ACCEPT
post-up   iptables -A FORWARD -d 192.168.10.100 -p tcp --dport 8080 -j ACCEPT
post-down iptables -D FORWARD -d 192.168.10.100 -p tcp --dport 80 -j ACCEPT 2>/dev/null || true
post-down iptables -D FORWARD -d 192.168.10.100 -p tcp --dport 443 -j ACCEPT 2>/dev/null || true
post-down iptables -D FORWARD -d 192.168.10.100 -p tcp --dport 8080 -j ACCEPT 2>/dev/null || true
#
post-up   iptables -A FORWARD -d 192.168.10.100 -p tcp --dport 3000:8000 -j ACCEPT
post-down iptables -D FORWARD -d 192.168.10.100 -p tcp --dport 3000:8000 -j ACCEPT 2>/dev/null || true

