set dotenv-load

# when: 
# `--volume jellyfin-cache:/cache:Z` - source:destination:options, Z - zfs storage driver, for 

# --device /dev/dri:/dev/dri:rwm \ - ?

version := '0.1.1'
tmpdir := `mktemp -du`

gen-env username password:
  echo "CONTAINERS_S3_USER={{username}}" >> .env
  echo "CONTAINERS_S3_PASSWORD={{password}}" >> .env

[doc("""
jellyfin image use 1000 (jellyfin user) and host use same 1000 user (STOREDIR also have 1000)
added --user UID:GID if STOREDIR have another permissions
""")]
podman-rund-jellyfin:
    podman run \
      -p 8096:8096/tcp \
      --rm \
      --name media_server \
      --device nvidia.com/gpu=0 \
      --volume jellyfin-cache:/cache:Z \
      --volume jellyfin-config:/config:Z \
      --volume $STOREDIR/downloads:/media:Z \
      docker.io/jellyfin/jellyfin:latest

podman-rund-minio:
  podman run \
    --rm \
    --detach \
    --label "io.containers.autoupdate=registry" \
    --name s3_server \
    --publish 9000:9000 \
    --publish 9001:9001 \
    --user $(id -u):$(id -g) \
    --userns keep-id \
    --volume $STOREDIR/containers/s3:/data \
    -e "MINIO_ROOT_USER=$CONTAINERS_S3_USER" \
    -e "MINIO_ROOT_PASSWORD=$CONTAINERS_S3_PASSWORD" \
    quay.io/minio/minio server /data --console-address ":9001"

podman-rund-esphome:
  podman run --rm \
    -p 6052:6052 \
    -e ESPHOME_DASHBOARD_USE_PING=true \
    -it ghcr.io/esphome/esphome

podman-rund-vaultwarden:
   podman run --rm --detach --name vaultwarden \
    --env DOMAIN="http://vw.localhost" \
    --volume vaultwarden:/data/ \
    --publish 127.0.0.1:8097:80 \
    docker.io/vaultwarden/server:latest

[group: "openbb"]
podman-openbb-build:
  podman build -f ./openbb.containerfile -t openbb-platform-demo:latest .

# ex: just podman-openbb-build podman-openbb-rund
[group: "openbb"]
podman-openbb-rund:
  podman run -it --rm -p 6900:6900 openbb-platform-demo:latest 

podman-rund-vert:
  podman run --rm \
    -p 3000:80 \
    --name "vert" \
    ghcr.io/vert-sh/vert:latest

mod test
