set dotenv-load

# when: 
# `--volume jellyfin-cache:/cache:Z` - source:destination:options, Z - zfs storage driver, for 

#--device /dev/dri:/dev/dri:rwm \ - ?

gen-env username password:
  echo "CONTAINERS_S3_USER={{username}}" >> .env
  echo "CONTAINERS_S3_PASSWORD={{password}}" >> .env

podman-rund-jellyfin:
  podman run \
    --rm \
    --detach \
    --label "io.containers.autoupdate=registry" \
    --name media_server \
    --publish 8096:8096/tcp \
    --user $(id -u):$(id -g) \
    --userns keep-id \
    --device nvidia.com/gpu=0 \
    --volume jellyfin-cache:/cache:Z \
    --volume jellyfin-config:/config:Z \
    --mount type=bind,source=$STOREDIR,destination=/media,ro=true,relabel=private \
    docker.io/jellyfin/jellyfin:latest


podman-rund-minio:
  podman run \
    --rm \
    --detach \
    --label "io.containers.autoupdate=registry" \
    --name s3_server \
    --publish 9000:9000 \
    --publish 9001:9001 \
    --user $(id -u):$(id -g) \
    --userns keep-id \
    --volume $STOREDIR/containers/s3:/data \
    -e "MINIO_ROOT_USER=$CONTAINERS_S3_USER" \
    -e "MINIO_ROOT_PASSWORD=$CONTAINERS_S3_PASSWORD" \
    quay.io/minio/minio server /data --console-address ":9001"


# https://podman-desktop.io/docs/podman/gpu
podman-test-nvidia:
  podman run --rm \
    --device nvidia.com/gpu=all \
    nvidia/cuda:12.9.1-base-ubuntu20.04 \
    nvidia-smi


podman-rund-vert:
  podman run --rm \
    -p 3000:80 \
    --name "vert" \
    ghcr.io/vert-sh/vert:latest

podman-rund-dokku:
  echo "TODO"
  # podman run 
