networks:
  dev-proxy:
    external: true

  internal:
    name: "devlab.localhost"
    driver: bridge

services:
  traefik:
    image: docker.io/library/traefik:latest
    container_name: devlab.localhost-proxy
    networks:
      - dev-proxy
      # - internal
    ports:
      # http port
      - 80:80
      # web ui
      - 8080:8080
    environment:
      TM_AUTH_TOKEN: ${TM_AUTH_TOKEN}
    command: --api.insecure=true --providers.docker
    volumes:
      - ./traefik:/etc/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /var/run/podman.sock:/var/run/docker.sock:ro
      # - /var/run/podman/podman.sock:/var/run/podman/podman.sock:ro
