networks:
  dev-proxy:
    external: true

services:
  whoami:
    image: docker.io/containous/whoami
    container_name: devalb.localhost-whoami
    networks:
      - dev-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${TM_DOMAIN_NAME}`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
