name: devlab-infra-zoo-kafka-cluster

services:
  ui:
    image: provectuslabs/kafka-ui
    ports:
      - 8090:8080
    depends_on:
      - zookeeper
      - kafka-1
    environment:
      KAFKA_CLUSTERS_0_NAME: devlab-kafka-cluster-0
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zoo-1:2181

  zookeeper:
    hostname: zoo-1
    image: docker.io/bitnami/zookeeper
    ports:
      - 2181
      - 2888
      - 3888
    environment:
      ZOO_SERVER_ID: 1
      ZOO_SERVERS: 0.0.0.0:2888:3888
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka-1:
    hostname: kafka-1
    image: docker.io/bitnami/kafka
    ports:
      - 29092
      - 9092
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo-1:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka-1:9092,EXTERNAL://kafka-1:29092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zookeeper
    
  kafka-2:
    hostname: kafka-2
    image: docker.io/bitnami/kafka
    ports:
      - 29093
      - 9093
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo-1:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9093,EXTERNAL://:29093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka-2:9093,EXTERNAL://kafka-2:29093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zookeeper

deploy:
  resources:
    limits:
      cpus: "4"
      memory: 2G
