set dotenv-load


[doc(""" Terraform prox command, autoloading dotenv
  ex:
    - just tf init
    - just tf plan
    - just tf apply
""")]
tf *ARGS:
  terraform {{ ARGS }}


test-auth:
  @echo $PM_USER $PM_PASS
  curl -I -X GET "https://edge.lan:8006/api2/json/cluster/resources" -H "Authorization: PVEAPIToken={$PM_USER}!{$PM_PASS}"
